print("Helló üdv itt!")
print("23*12=")
print("Alma"+"körte")
print("Alma","körte")
print("Alma","körte",sep=",")
print("Alma"+"körte","barack" , sep="\a") # azonos "" 
print("Alma"+"körte","barack", sep="\b")
print("Alma"+"körte","barack" , sep="\f")
print("Alma"+"körte","barack" , sep="\r")
print("Alma"+"körte","barack" , sep="\n")
print("szia\\ pipacs")
print("szia\' pipacs")
print("szia ' pipacs")
print("szia" "pipacs")
print("szia")
print("pipacs")
